name: K8s Infra CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=lanchonete-k8s-infra fmt -check -recursive
        continue-on-error: true

      - name: Terraform validate
        id: validate
        run: terraform -chdir=lanchonete-k8s-infra validate

      - name: Terraform plan
        id: plan
        run: terraform -chdir=lanchonete-k8s-infra plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=lanchonete-k8s-infra apply -input=false tfplan

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm charts
        run: helm lint ./lanchonete-k8s-infra/charts/lanchonete-chart
